
TYPO3:
  TypoScript:
    defaultContext:
      Flownative.Compressor: Flownative\Neos\Compressor\CompressionHelper
Neos:
  Neos:
    typoScript:
      autoInclude:
        Flownative.Neos.Compressor: true
